### ISSUE TITLE
Mute ydb/core/kqp/ut/spilling/KqpScanSpilling.SelfJoinQueryService

### ISSUE THREAD

**Issue by maximyurchuk** [ydb-platform/ydb#11353]
Mute:
ydb/core/kqp/ut/spilling/KqpScanSpilling.SelfJoinQueryService

Branch:
main

**Add line to [muted_ya.txt](https://github.com/ydb-platform/ydb/blob/main/.github/config/muted_ya.txt):**
```
ydb/core/kqp/ut/spilling KqpScanSpilling.SelfJoinQueryService
```

Owner: TEAM:@ydb-platform/qp

**Read more in [mute_rules.md](https://github.com/ydb-platform/ydb/blob/main/.github/config/mute_rules.md)**

**Summary history:** 
 KqpScanSpilling.SelfJoinQueryService: Flaky last 8 days, at 2024-11-07: success_rate 64%, Pass:16 Fail:9 Mute:0 Skip:0

**Test run history:** [link](https://datalens.yandex/34xnbsom67hcq?full_name=__in_ydb%2Fcore%2Fkqp%2Fut%2Fspilling%2FKqpScanSpilling.SelfJoinQueryService)

More info in [dashboard](https://datalens.yandex/4un3zdm0zcnyr)

**Comment by vladl2802** [comment]
Should be fixed after [this commit](https://github.com/ydb-platform/ydb/commit/d18411023462c7bfbcc27f47ab8f1b6adada8f47)

**Comment by naspirato** [comment]
### Mute control list (managed by bot)
Issue #11353 | part 1/1

1. **Default path.** This issue will close automatically once **every** test here has been stable (green in CI, no new failures) for **7** full days under the normal mute rules.
2. **You fixed only some tests.** Tick **`[x]`** next to those tests. That opts them into a **faster path**: after a **48-hour** cooldown, only **2** consecutive good days are required before they can be unmuted, instead of **7**.
3. **You fixed all tests.** You can simply **close this issue yourself** (not via a bot). The bot will treat every still-active test the same as in (2): **48h** wait, then the **2-day** short window instead of **7**.

- [x] `ydb/core/kqp/ut/spilling/KqpScanSpilling.SelfJoinQueryService`
  

---
**Legend**
- `[ ]` — default **7-day** stability path.
- `[x]` — short **2-day** path after the cooldown.
- ~~Strikethrough~~ — test already unmuted or removed from this issue.

_Each test may have a hidden metadata line underneath (for automation only)._

**Comment by naspirato** [comment]
### Manual fast-unmute status — issue #11353

Tests currently opted in (**[x]** or auto after human close):
- `ydb/core/kqp/ut/spilling/KqpScanSpilling.SelfJoinQueryService` => **pending_fast_unmute_wait** — **2-day** short window from **14 Apr 2026, 12:22 UTC** (request **12 Apr 2026, 12:22 UTC**).

**Rule:** after the **short window** time on each line (UTC), the mute updater counts a **2-day** green streak (≥4 runs, 0 fail/mute).

_This comment is updated on every bot run; unchecked tests disappear from the list._

**Comment by naspirato** [comment]
Fast-unmute flow enabled for issue #11353.

Reason:
- issue was closed manually by @vladl2802
- linked PR found in Development context

Linked PRs:
- #11350 (MERGED): https://github.com/ydb-platform/ydb/pull/11350

Result:
- tests from this issue become eligible for 1-day unmute window in mute update flow
