### ISSUE TITLE
tpch10000 q18. WideCombiner single bucket don't fit into memory

### ISSUE THREAD

**Issue by lll-phill-lll** [ydb-platform/ydb#11416]
https://github.com/ydb-platform/ydb/blob/65dc86e989300e998b03fb414beccebed687d785/ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp#L481

Bt:
https://paste.yandex-team.ru/d7a045b0-8309-4f2f-bc6d-56c514da5928

**Comment by vladl2802** [comment]
For point (2) I've tried xxh64 (those flame graphs are in previous comment and below also) and fibonacci hashing (its flame graph is below).

So for some reason (that I can't explain for now) xxh64 seems faster than fibonacci even so fibonacci should require less operations to compute. But I am not sure about that point, because execution is really unstable.

So we will use xxh64 for now. Further progress can be made in block combine or/and after https://github.com/ydb-platform/ydb/issues/11591

### Fibonacci hashing (as [here](https://github.com/ydb-platform/ydb/blob/c8e6180cc6fc2d5276882e6a40cb4f7e189db42c/yql/essentials/minikql/comp_nodes/mkql_rh_hash.h#L219))
![mem-fibonacci](https://github.com/user-attachments/assets/326d4a34-61bf-48ad-91f4-b1ba7d66b989)

### xxh64
![mem-xxh](https://github.com/user-attachments/assets/1bf1b9a7-1b83-4013-9401-f86a7e3938de)

**Comment by lll-phill-lll** [comment]
2h run results:
https://nda.ya.ru/t/qWfckDan79ezxP
spilling plot: https://nda.ya.ru/t/wp-yyyx779ezvp

Looks suspicious. Like it worked only for 30 mins

**Comment by lll-phill-lll** [comment]
https://nda.ya.ru/t/dlVeCoho79f4uA
![Uploading a08810f4946fbb1c.svg…]()

Error after 32 mins
