### ISSUE TITLE
TExecuteDistributedEraseTxUnit: VERIFY failed

### ISSUE THREAD

**Issue by CyberROFL** [ydb-platform/ydb#2758]
```
VERIFY failed
  ydb/core/tx/datashard/execute_distributed_erase_tx_unit.cpp:97
  Execute(): requirement ok failed
```

**Comment by snaury** [comment]
I think page fault happens because index has uncommitted changes and BreakWriteConflicts page faults when looking for conflicts. I suspect it's enough to return `Restart` instead of aborting, but I'm not sure since indexes have simplified code path (e.g. they work without user db, and won't see their own changes on volatile upgrade, but it's probably not relevant since changeCollector is left as nullptr for indexes, so it probably doesn't matter).

Btw, current code relies on `Execute` being called at most once, but the index case runs for each readset. I suspect there's always a single readset, but the `for` loop looks error prone.

**Comment by ijimiji** [comment]
Hi! Any updates so far?
