### ISSUE TITLE
Investigate NodeBroker unavailability

### ISSUE THREAD

**Issue by CyberROFL** [ydb-platform/ydb#3354]

**Comment by pixcc** [comment]
The problem occurs when many dynamic nodes are removed from the cluster. After 2-3 epochs have passed, the deleted dynamic nodes are completely removed from the `Node Broker` and from the cache of the `Dynamic Nameserver` residing on each node.

But they remain in `Hive` tablet. Components learn about nodes from `Hive`, make requests to these nodes, and since these nodes are not in the cache of the `Dynamic Nameserver`, the `Dynamic Nameserver` sends requests to the `Node Broker`. `Dynamic Nameserver` doesn't cache negative responses from node broker.

Only `Embedded UI` and `HealthCheck` get information about nodes from `Hive`. In `24-1` it was added that each base periodically makes a healthcheck request. `Healthcheck` get information about nodes from the root `Hive` that tracks all nodes in the cluster.
