### ISSUE TITLE
Any plans to split Blobdb

### ISSUE THREAD

**Issue by ddorian** [ydb-platform/ydb#37]
Hi,

Are there any plans to split Blobdb into its own project?

**Comment by fomichev3000** [comment]
By name "Blobdb" do you mean YDB BlobStorage layer? BlobStorage or DistributedStorage is distributed key value database with a very specific API. This API is designed exclusively for Tablets layer. For instance, "key" has a very specific format instead of being an ordinary string. BlobStorage has operations like "Block" to gather a quorum of disks for tablet's master election. So we don't have plans to set off BlobStorage into a separate project.

What is your need? If you want to use YDB as a platform it's better to consider using tablet's layer.

**Comment by ddorian** [comment]
Thanks. Thought it was as a general kv with erasure coding.
