### ISSUE TITLE
#2006 Kikimr cluster or one of its subsystems is overloaded. (S_ERROR)

### ISSUE THREAD

**Issue by aHsirG** [ydb-platform/ydb#46]
При тестировании из java-client судя про ошибки проблемы шарда
com.yandex.ydb.core.UnexpectedResultException: expected success result, code: OVERLOADED, issues: [#1060 Execution (S_ERROR)
  #2006 Kikimr cluster or one of its subsystems is overloaded. (S_ERROR)
  Error executing transaction (ProxyShardOverloaded): One or more of affected datashards are overloaded, try again (S_ERROR)
  Data shard errors: [WRONG_SHARD_STATE] Rejecting data TxId 281482397066193 because datashard 72075186256745705: decided to reject due to given RejectProbability
 (S_ERROR)]
        at com.yandex.ydb.core.Result$Fail.newException(Result.java:217) ~[ydb-sdk-core-1.10.5.jar!/:na]
        at com.yandex.ydb.core.Result$Fail.expect(Result.java:169) ~[ydb-sdk-core-1.10.5.jar!/:na]
        at com.griphon.service.ArticleServices.saveArticleTransaction(ArticleServices.java:123) ~[classes!/:0.0.1-SNAPSHOT]
        
при вставке может отсекать чуть ли не половину запросов, возникает как при YDB в Cloud, так и при собственной установки. Такой троттлинг может и понятен, но необходимо либо понимать как ограничивать тогда нагрузку, либо в идеале, чтобы транзакция выполнялась но дольше.
Сценарий теста, вставка в пустую таблицу от 0 до N строк с уникальными не пересекающимися ключами

**Comment by snaury** [comment]
Hi, thank you for your interest! YDB is historically designed with as little buffering as possible, and it's not always possible to ingest all incoming data, either because we cannot write it to disk and compact fast enough. In those cases we reply with our standard OVERLOADED error code, and user application is expected to retry the request with some exponential backoff.

It's possible you see this error because you are not using our standard retry wrappers. For java please see `SessionRetryContext` in our examples.

**Comment by aHsirG** [comment]
Thanks, SessionRetryContext is good solution and fixs problem. 
In Jdbc version is enabled?
