### ISSUE TITLE
support setting implTable config parameters on alter table add index

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb#4955]
YDB Backup files store information about index table partitioning config and other parameters.
Internal implementation of `Alter table add index` operation must provide a way to set implTable configuration, e.g. number of partitions and their boundaries

**Comment by jepett0** [comment]
Some thoughts on the problem:

We need to decide on the optimal protocol for backups and restores of indices. The usual way to restore a scheme object is to execute the appropriate CreateSomeObjectRequest from the public API from the backup. However, index table partitioning settings cannot be specified in the CreateTableRequest currently.

We need to choose one of the solutions:
- add index table partitioning settings description in the CreateTableRequest from public API
- recreate a table with indices using CreateTableRequest + a AlterTableRequests for each indexImplTable

It seems that @CyberROFL is ok with the former solution, but would like to be able to execute AlterTableRequest not on the indexImplTable (because it is a part of the implementation), but on the index object itself.

AlterTableRequest on indexImplTable vs. AlterTableRequest on the index object itself:

Cons:
1) We don't need to know implementation details of index table.

Pros:
1) Such a backup / restore protocol could be implemented without any changes to the YDB code.
2) Maybe it is ok for backup / restore to know index tables implementation details, because this procedures will not be a part of the user's code, but a part of backup / restore system.
3) It is natural for a table to be a target of AlterTableRequest. One could argue that it is not obvious that it is possible to alter indexImplTable partitioning settings by issuing AlterTableRequest on its parent (the index object).

**Comment by jepett0** [comment]
PR:
https://github.com/ydb-platform/ydb/pull/5119
